addons:
  apt:
    packages:
      - python-scipy
      - python-yaml

git:
  submodules: false

matrix:
  include:
    - env: LANG=crystal
      language: crystal
    - env: LANG=js
      language: node_js
      node_js: "6"
    - env: LANG=java  JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: LANG=som   JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: LANG=somns JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: LANG=pharo
      language: smalltalk
      smalltalk: Pharo-5.0
    - env: LANG=squeak
      language: smalltalk
      smalltalk: Squeak-5.1
    - env: LANG=rsqueak
      language: smalltalk
      smalltalk: Squeak-5.1
      addons:
        apt:
          packages:
            - python-scipy
            - python-yaml
            - libsdl2-2.0-0
            - libffi6
    - env: LANG=ruby
      language: ruby
      rvm: 2.3.1

install:
  - pip install --user ReBench
  - if [ "$LANG" = "ruby" ]; then gem install rubocop;   fi
  - if [ "$LANG" = "js" ];   then npm install -g jshint; fi

script:
  - implementations/build-$LANG.sh && rebench test.conf test-$LANG
  - implementations/build-$LANG.sh style
